spring:
  application:
    name: training
  datasource:
    url: jdbc:mysql://localhost:3306/store_template?DatabaseIfNotExist=true
    username: root
    password: SUNday@247
#  jpa:
#    hibernate:
#      ddl-auto: create
#  flyway:
#    baseline-on-migrate: true

app:
  page-size: 10
stripe:
  apiURL: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,NGN,CAD
payment-gateway: paypal
email:
  host: gmail.com
  name: owolabi.fawemimo@interswitchng.com
  port: 8080
  ssl: true
