spring:
  application:
    name: training
app:
  page-size: 10
stripe:
  apiURL: https://api.stripe.com
  timeout: 1000
  enabled: true
  supported-currencies: USD,NGN,CAD
payment-gateway: paypal
email:
  host: ${EMAIL_HOST}
  name: owolabi.fawemimo@interswitchng.com
  port: 8080
  ssl: true
